package com.example.modelo;
// Generated 23 feb 2023 11:07:05 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Shows generated by hbm2java
 */
@Entity
@Table(name = "shows", catalog = "netflix")
public class Shows implements java.io.Serializable {

	private String showId;
	private String tipo;
	private String titulo;
	private String director;
	private String actores;
	private String pais;
	private String fecha;
	private int anyoLanzamiento;
	private String rating;
	private String duracion;
	private String tags;
	private String descripcion;

	public Shows() {
	}

	public Shows(String showId, String tipo, String titulo, int anyoLanzamiento, String tags, String descripcion) {
		this.showId = showId;
		this.tipo = tipo;
		this.titulo = titulo;
		this.anyoLanzamiento = anyoLanzamiento;
		this.tags = tags;
		this.descripcion = descripcion;
	}

	public Shows(String showId, String tipo, String titulo, String director, String actores, String pais, String fecha,
			int anyoLanzamiento, String rating, String duracion, String tags, String descripcion) {
		this.showId = showId;
		this.tipo = tipo;
		this.titulo = titulo;
		this.director = director;
		this.actores = actores;
		this.pais = pais;
		this.fecha = fecha;
		this.anyoLanzamiento = anyoLanzamiento;
		this.rating = rating;
		this.duracion = duracion;
		this.tags = tags;
		this.descripcion = descripcion;
	}

	@Id

	@Column(name = "show_id", unique = true, nullable = false, length = 5)
	public String getShowId() {
		return this.showId;
	}

	public void setShowId(String showId) {
		this.showId = showId;
	}

	@Column(name = "tipo", nullable = false, length = 7)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "titulo", nullable = false, length = 104)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	@Column(name = "director", length = 208)
	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	@Column(name = "actores", length = 771)
	public String getActores() {
		return this.actores;
	}

	public void setActores(String actores) {
		this.actores = actores;
	}

	@Column(name = "pais", length = 123)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "fecha")
	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	@Column(name = "anyo_lanzamiento", nullable = false)
	public int getAnyoLanzamiento() {
		return this.anyoLanzamiento;
	}

	public void setAnyoLanzamiento(int anyoLanzamiento) {
		this.anyoLanzamiento = anyoLanzamiento;
	}

	@Column(name = "rating", length = 8)
	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	@Column(name = "duracion", length = 10)
	public String getDuracion() {
		return this.duracion;
	}

	public void setDuracion(String duracion) {
		this.duracion = duracion;
	}

	@Column(name = "tags", nullable = false, length = 79)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@Column(name = "descripcion", nullable = false, length = 248)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
